title: Hello, Skywing's Develop Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: skywing # add your name
author-img: skywingLogo.gif # add your photo
about-author: I am Java Developer. # add description
# social-twitter:  # add your Twitter handle
social-facebook: skywingz # add your Facebook handle
social-github: skywingzz # add your Github handle
social-email: skywing.bae@gmail.com # add your Email address

# Disqus
discus-identifier: skywingBlog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
